[project]
name = "jev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-chroma>=1.1.0",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.6",
    "langchain-classic>=1.0.8",
    "langgraph>=1.2.12",
    "chromadb>=1.5.9",
    "rank-bm25>=0.2.2",
    "pymupdf>=1.28.2",
    "sentence-transformers>=6.1.0",
    "typesafe-sdk>=0.7.2",
    "pandas>=3.0.6",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "tiktoken>=0.14.0",
    "jupyter>=1.1.1",
    "ipykernel>=7.3.0",
    "python-dotenv>=1.2.3",
    "nbclient>=0.11.0",
    "nbformat>=5.11.1",
]
